[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[lib]
name = "virt"
path = "src/virt/lib.rs"

[[bin]]
name = "hello-world"

[[bin]]
name = "echo"

[[bin]]
name = "day1"
